---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create the system group
  group:
    name: "{{ system_group_name }}"
    state: "present"
    system: "yes"
  notify: Restart OpenStack service(s)

- name: Create the system user
  user:
    name: "{{ system_user_name }}"
    group: "{{ system_group_name }}"
    comment: "{{ system_comment }}"
    shell: "{{ system_shell }}"
    system: "yes"
    createhome: "yes"
    home: "{{ system_home_folder }}"
    generate_ssh_key: "yes"
  notify: Restart OpenStack service(s)

- name: Create directories
  file:
    path: "{{ item.path|default(omit) }}"
    dest: "{{ item.dest|default(omit) }}"
    src: "{{ item.src|default(omit) }}"
    state: "{{ item.state|default('directory') }}"
    owner: "{{ item.owner|default(system_user_name) }}"
    group: "{{ item.group|default(system_group_name) }}"
    mode: "{{ item.mode|default('0755') }}"
  with_items: required_directories
  notify: Restart OpenStack service(s)

- name: Create sudoers file
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers.d/{{ system_user_name }}_sudoers"
    mode: "0440"
    owner: "root"
    group: "root"
  notify: Restart OpenStack service(s)
